#!/bin/bash -eu

cd $(dirname $0)/..

# Clean up at the end
trap "docker-compose down --volumes" 0

docker volume create --name=middy-npm-cache

# Install deps
docker-compose run --rm dev yarn install

# Give a shell or run what's passed in as arguments
docker-compose run --rm --no-deps --service-ports dev "${@-sh}"
